CREATE TABLE T_FEED (
	C_ID INT AUTO_INCREMENT PRIMARY KEY,
	C_RSS_SOURCE VARCHAR(20),
	C_TITLE VARCHAR(256),
	C_DESCRIPTION VARCHAR(4096),
	C_LINK VARCHAR(256),
	C_GUID VARCHAR(256),
	C_PUBLISHED DATETIME,
	C_CATEGORY VARCHAR(20),
	C_SUB_CATEGORY VARCHAR(20),
	C_CREATED DATETIME
);